### ISSUE TITLE
colors.vim plugin overwrites colorscheme to base16 themes

### ISSUE THREAD

**Issue by shunwen** [dotphiles/dotvim#6]
https://github.com/dotphiles/dotvim/blob/master/plugin/settings/colors.vim#L40 . It overwrites the colorscheme set in `~/.vimrc`, which makes it impossible for user to use customized themes in terminal vim.

**Comment by benohara** [comment]
Missed this, i'll have a look and update it to work.

**Comment by TheLonelyGhost** [comment]
Also poses issues if the 'general' vundle isn't not installed for any reason. Would require the end user to install the base16 plugin to *not* encounter errors.

If this is desired, include the base16 plugin by default instead of the general vundle. Else we should leave off the above mentioned else condition entirely.

**Comment by benohara** [comment]
https://github.com/dotphiles/dotvim/pull/10 is a solution?

vundle should get installed by vundle.vim if its not there

**Comment by TheLonelyGhost** [comment]
#10 seems legit. Will check it out and get back to you.

**Comment by chairfield** [comment]
https://github.com/dotphiles/dotvim/pull/10 works for me, and it's now been merged into `master`.

**Comment by bardo** [comment]
Works for me as well. Ready to close this issue? :)
